services:
  gestorpro.api:
    image: ${DOCKER_REGISTRY-}gestorproapi
    build:
      context: .
      dockerfile: GestorPro.Api/Dockerfile
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
